### ISSUE TITLE
getting error after immediately downloading docker image

### ISSUE THREAD

**Issue by rohitbhoite** [instrumentisto/flutter-docker-image#15]
What could we the root cause of this issue?

Jenkinsfile log:

```
Digest: sha256:9316fc85c8be21da4605d4111cd6cf4128e0fb8aa5b7745fb28a27ecece37f74
Status: Downloaded newer image for instrumentisto/flutter:3.19.6-androidsdk34-r0
docker.io/instrumentisto/flutter:3.19.6-androidsdk34-r0

What's Next?
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x8e85f4]

goroutine 8 [running]:
fmt.Fprintln({0x0, 0x0}, {0xc0000cbf78, 0x1, 0x1})
	fmt/print.go:285 +0x54
github.com/docker/cli/cli/config.LoadDefaultConfigFile({0x0, 0x0})
	github.com/docker/cli@v20.10.7+incompatible/cli/config/config.go:157 +0xe5
github.com/docker/compose-cli/cli/mobycli.hubLoggedIn.func1()
	github.com/docker/compose-cli/cli/mobycli/scout_suggest.go:92 +0x2a
created by github.com/docker/compose-cli/cli/mobycli.hubLoggedIn
	github.com/docker/compose-cli/cli/mobycli/scout_suggest.go:91 +0x6a
```

Jenkinsfile:

```
node {

    env.DEBIAN_FRONTEND = 'noninteractive'
    env.TZ = 'Europe/Istanbul'

    docker.image("instrumentisto/flutter:3.19.6-androidsdk34-r0").inside("${configs.dockerImage.arguments}") {
   }
}
```

**Comment by sunil-kannan** [comment]
I am also getting same error. Have you found the solution?

**Comment by tyranron** [comment]
Judging from the provided stack trace, the issue is with the Docker Compose CLI installation. There is nothing we can do about it from this image site.

Not, that specified [`github.com/docker/compose-cli`](https://github.com/docker/compose-cli) is archived long ago. I think it panics because doesn't meet latest Docker Hub changes.
